### ISSUE TITLE
There is no hook for departed relations

### ISSUE THREAD

**Issue by tbaumann** [juju-solutions/layer-beats-base#16]
There is no cache.set('beat.logstash' ...), cache.set('beat.elasticsearch', ...) or cache.set('beat.kafka', ...) that would remove entries from cache if a unit departs from the relation or even the whole relation is removed.
Therefore it will always keep host in the config, even if they are no longer valid.

**Comment by tbaumann** [comment]
Related. Does this pattern even make sense?
https://github.com/juju-solutions/layer-beats-base/blob/master/reactive/beats_base.py#L24

The correct truth will be in the relations. Why read the cache in the first place?

**Comment by tbaumann** [comment]
Catching this 'event' https://github.com/juju-solutions/interface-elastic-beats/blob/master/requires.py#L18 (conv.remove_state('{relation_name}.available')) is not really straight forward. :(

**Comment by lazypower** [comment]
I agree Torsten. A lot of this was experimental and pioneering code with having a shared base layer that top layers could interface with. (i'm going from fuzzy details since I haven't really looked at this code in many months) Not having those relations tightly bound in this layer were a problem area and why i think i went with unitdata to do the translations between layers, but if there's a better pattern here I'm certainly going to encourage you to explore and leverage that.

When this project started it was with the understanding we were going to invest some time in this software stack. The resultant reality was not one of having excess time to sort through the cut corners.

Keep the comment thread going though and with the help of community members like @jamesbeedy and @galgalesh i'm certain we can turn the base layer into something more straight forward following -current- charming best practices.

Also good catch on the cache removal not being there.

**Comment by tbaumann** [comment]
I'm working on kludgy workaround. It adds a lot of complexity. I might have something to propose soon.
The main issue is the damn interface. The current version of reactive interfaces is just very dumb for that. :(
The main issue is, that it's relatively simple to catch the falling edge of the *.connected state. But it will not have the context parameter from the interface.
And because interfaces are unreliable I don't think I can quite rely on the fact that nothing is connected when the .connected state vanishes. (from previous experience with other interfaces)

**Comment by lazypower** [comment]
Could you expand on:

>  I don't think I can quite rely on the fact that nothing is connected when the .connected state vanishes.

The way i understand it is that this state should always be set so long as something is attached at that interface scope, and that state will only vanish if the interface explicitly removes it (again, depending on scope)

cc @johnsca  - can you confirm/deny my analysis here? It sounds like we may have a mismatch on understanding of relationship scopes and how their associated states remain set on the units.

**Comment by tbaumann** [comment]
Honestly, I wonder the same. Perhaps my understanding of the departed hook is incorrect. Though I remember having those issues many times with my own charms.
But I have to admit, I haven't seen those issues in this charm yet. I wonder if somethig is different...

What I'm talking about is, the interface in line 15 catches the departed hook. And when that code is called it unconditionally removes the *.available state.
Suppose three nodes are connected. One leaves, two should be left but the hook is called and the state removed.
I should have time to work a little more on this issue. I will let you know what I find.
Truth is, I just remembered that I tested exactly that scenario a few days ago with the reading from cache first in cache_logstash_data(logstash) and I actually remember quite clearly that it worked fine, execept for the last connection because ther was no hook to catch the 'nobody connected' situation.

Maybe what you said about scopes is the key. My previous quite negative experience with that was with peer relations.

**Comment by tbaumann** [comment]
Apparently, my bad experience with reactive interfaces does not apply here. I will try to understand that another day.
The commits above should fix the issue. In favour of less complexity, I didn't make the remove cache handlers trigger on the falling edge of *.available.
That way render will be called a few more times than necessary. But it stays more readable.

I can't say I like this solution. But I could not find a way to make it clearer.

**Comment by tbaumann** [comment]
PS: Sorry this is based on my kafka branch. I can manually cherry pick those changes into master if you prefer.

**Comment by lazypower** [comment]
Would you mind terribly cherry picking them into their own branch so we can resolve this cleanly and evaluate the kafka bits in their own pr's? :)
