### ISSUE TITLE
Replace manual hook with juju-info interface layer

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-beats-base#3]
https://github.com/juju-solutions/interface-juju-info

The interface will need some changes to support this use-case.

**Comment by lazypower** [comment]
@johnsca the one thing the manual hook does is it pulls in the related units charm-name so it can then in turn set the 'shipper' value to what its principal units name may be. Bridging the gap between "beats info" and Juju. 

Is this something we can reasonably plug into that interface and expose via the relationship data? such as the following:

``` python
from os import getenv

host = getenv('JUJU_REMOTE_UNIT').replace('/', '-')
```

**Comment by johnsca** [comment]
This breaks encapsulation slightly, but we could certainly create a method on the interface, and I'd like to see this info become more accessible with the new approach to reactive relations in 2.0.

``` python
@when('beats-host.connected')
def connected(beats_host):
    principal_name = beats_host.conversation().units[0]
    ...
```

**Comment by kwmonroe** [comment]
Fixed by (or rather, this is no longer an issue because of) #32.

We've been doing a reactive principal_name cache for a while now; no need for a custom hook.
